2024-10-04 11:55:40,602 INFO    MainThread:150793 [wandb_setup.py:_flush():76] Current SDK version is 0.16.3
2024-10-04 11:55:40,602 INFO    MainThread:150793 [wandb_setup.py:_flush():76] Configure stats pid to 150793
2024-10-04 11:55:40,602 INFO    MainThread:150793 [wandb_setup.py:_flush():76] Loading settings from /home/msinnona/.config/wandb/settings
2024-10-04 11:55:40,602 INFO    MainThread:150793 [wandb_setup.py:_flush():76] Loading settings from /mnt/disk2/msinnona/visdecode/eurographics/wandb/settings
2024-10-04 11:55:40,602 INFO    MainThread:150793 [wandb_setup.py:_flush():76] Loading settings from environment variables: {}
2024-10-04 11:55:40,602 INFO    MainThread:150793 [wandb_setup.py:_flush():76] Inferring run settings from compute environment: {'program': '<python with no main file>'}
2024-10-04 11:55:40,602 INFO    MainThread:150793 [wandb_setup.py:_flush():76] Applying login settings: {'api_key': '***REDACTED***'}
2024-10-04 11:55:40,602 INFO    MainThread:150793 [wandb_setup.py:_flush():76] Applying login settings: {'api_key': '***REDACTED***'}
2024-10-04 11:55:40,602 INFO    MainThread:150793 [wandb_init.py:_log_setup():526] Logging user logs to /mnt/disk2/msinnona/visdecode/eurographics/wandb/run-20241004_115540-l2syfkiu/logs/debug.log
2024-10-04 11:55:40,602 INFO    MainThread:150793 [wandb_init.py:_log_setup():527] Logging internal logs to /mnt/disk2/msinnona/visdecode/eurographics/wandb/run-20241004_115540-l2syfkiu/logs/debug-internal.log
2024-10-04 11:55:40,602 INFO    MainThread:150793 [wandb_init.py:init():566] calling init triggers
2024-10-04 11:55:40,602 INFO    MainThread:150793 [wandb_init.py:init():573] wandb.init called with sweep_config: {}
config: {}
2024-10-04 11:55:40,602 INFO    MainThread:150793 [wandb_init.py:init():591] re-initializing run, found existing run on stack: ss1izzn0
2024-10-04 11:55:40,604 INFO    MainThread:150793 [wandb_run.py:_finish():1970] finishing run martinsinnona/visdecode/ss1izzn0
2024-10-04 11:55:40,604 INFO    MainThread:150793 [jupyter.py:save_history():445] not saving jupyter history
2024-10-04 11:55:40,604 INFO    MainThread:150793 [jupyter.py:save_ipynb():373] not saving jupyter notebook
2024-10-04 11:55:40,605 INFO    MainThread:150793 [wandb_init.py:_jupyter_teardown():454] cleaning up jupyter logic
2024-10-04 11:55:40,605 INFO    MainThread:150793 [wandb_run.py:_atexit_cleanup():2210] got exitcode: 0
2024-10-04 11:55:40,605 INFO    MainThread:150793 [wandb_run.py:_restore():2193] restore
2024-10-04 11:55:40,605 INFO    MainThread:150793 [wandb_run.py:_restore():2199] restore done
2024-10-04 11:57:42,059 INFO    MainThread:150793 [wandb_init.py:init():616] starting backend
2024-10-04 11:57:42,059 INFO    MainThread:150793 [wandb_init.py:init():620] setting up manager
2024-10-04 11:57:42,063 INFO    MainThread:150793 [backend.py:_multiprocessing_setup():105] multiprocessing start_methods=fork,spawn,forkserver, using: spawn
2024-10-04 11:57:42,063 INFO    MainThread:150793 [wandb_init.py:init():628] backend started and connected
2024-10-04 11:57:42,075 INFO    MainThread:150793 [wandb_run.py:_label_probe_notebook():1295] probe notebook
2024-10-04 11:57:42,075 INFO    MainThread:150793 [wandb_run.py:_label_probe_notebook():1305] Unable to probe notebook: 'NoneType' object has no attribute 'get'
2024-10-04 11:57:42,075 INFO    MainThread:150793 [wandb_init.py:init():720] updated telemetry
2024-10-04 11:57:42,081 INFO    MainThread:150793 [wandb_init.py:init():753] communicating run to backend with 90.0 second timeout
2024-10-04 11:58:07,198 WARNING MsgRouterThr:150793 [router.py:message_loop():77] message_loop has been closed
2024-10-04 11:58:07,198 WARNING MsgRouterThr:150793 [router.py:message_loop():77] message_loop has been closed
